//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empire_Earth_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empire_Earth_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _unchecked {
            get {
                object obj = ResourceManager.GetObject("unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply recommended display.
        /// </summary>
        internal static string ApplyDisplayButton {
            get {
                return ResourceManager.GetString("ApplyDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible while {0} is running..
        /// </summary>
        internal static string BlockedByGameFormat {
            get {
                return ResourceManager.GetString("BlockedByGameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible while the {0} setup is running..
        /// </summary>
        internal static string BlockedBySetupFormat {
            get {
                return ResourceManager.GetString("BlockedBySetupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checked_disabled {
            get {
                object obj = ResourceManager.GetObject("checked_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap combo {
            get {
                object obj = ResourceManager.GetObject("combo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap combo_disabled {
            get {
                object obj = ResourceManager.GetObject("combo_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set by the setup for all users (only the setup changes it): {0}.
        /// </summary>
        internal static string CompatibilityAllUsersFormat {
            get {
                return ResourceManager.GetString("CompatibilityAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options apply to {0} for your Windows account..
        /// </summary>
        internal static string CompatibilityAppliesToFormat {
            get {
                return ResourceManager.GetString("CompatibilityAppliesToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix 8/16-bit colors (DWM8And16BitMitigation).
        /// </summary>
        internal static string CompatibilityDwmOption {
            get {
                return ResourceManager.GetString("CompatibilityDwmOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear memory allocations (HeapClearAllocation).
        /// </summary>
        internal static string CompatibilityHeapOption {
            get {
                return ResourceManager.GetString("CompatibilityHeapOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scaling by Windows (HIGHDPIAWARE).
        /// </summary>
        internal static string CompatibilityHighDpiOption {
            get {
                return ResourceManager.GetString("CompatibilityHighDpiOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change one option at a time and start the game to check it. If the game gets worse, undo the last ch[rest of string was truncated].
        /// </summary>
        internal static string CompatibilityHintMessage {
            get {
                return ResourceManager.GetString("CompatibilityHintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility options.
        /// </summary>
        internal static string CompatibilityHintTitle {
            get {
                return ResourceManager.GetString("CompatibilityHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility values of an older setup ({0}), which can cause black screens on Windows 7. Run the cu[rest of string was truncated].
        /// </summary>
        internal static string CompatibilityLegacyFormat {
            get {
                return ResourceManager.GetString("CompatibilityLegacyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Windows 7 and under Wine the launcher offers no compatibility options; the current setup sets non[rest of string was truncated].
        /// </summary>
        internal static string CompatibilityNotOffered {
            get {
                return ResourceManager.GetString("CompatibilityNotOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An older setup set "Run as administrator" for your account (~ RUNASADMIN). The online lobby should n[rest of string was truncated].
        /// </summary>
        internal static string CompatibilityRunAsAdminHint {
            get {
                return ResourceManager.GetString("CompatibilityRunAsAdminHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows compatibility mode is already set, so no second one is offered. If the setup set it for al[rest of string was truncated].
        /// </summary>
        internal static string CompatibilityVersionModeSet {
            get {
                return ResourceManager.GetString("CompatibilityVersionModeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CompatibilityWarningConfirm {
            get {
                return ResourceManager.GetString("CompatibilityWarningConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find advanced compatibility options. These options can solve compatibility problems or [rest of string was truncated].
        /// </summary>
        internal static string CompatibilityWarningText {
            get {
                return ResourceManager.GetString("CompatibilityWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 7 compatibility mode (WIN7RTM).
        /// </summary>
        internal static string CompatibilityWindows7Option {
            get {
                return ResourceManager.GetString("CompatibilityWindows7Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: set up by a newer launcher or setup; the launcher leaves them as they are..
        /// </summary>
        internal static string DefaultsStatusAppliedByNewerFormat {
            get {
                return ResourceManager.GetString("DefaultsStatusAppliedByNewerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the recommended settings are set up for your Windows account..
        /// </summary>
        internal static string DefaultsStatusAppliedFormat {
            get {
                return ResourceManager.GetString("DefaultsStatusAppliedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: installed by a newer setup than this launcher knows. The launcher changes no settings; please u[rest of string was truncated].
        /// </summary>
        internal static string DefaultsStatusNewerContractFormat {
            get {
                return ResourceManager.GetString("DefaultsStatusNewerContractFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the recommended settings are not set up for your Windows account yet..
        /// </summary>
        internal static string DefaultsStatusPendingFormat {
            get {
                return ResourceManager.GetString("DefaultsStatusPendingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: not set up yet, because several installations share these settings. "Reset game settings" sets [rest of string was truncated].
        /// </summary>
        internal static string DefaultsStatusWaitingForPlayFormat {
            get {
                return ResourceManager.GetString("DefaultsStatusWaitingForPlayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details have been written to {0}..
        /// </summary>
        internal static string DetailsWrittenToLogFormat {
            get {
                return ResourceManager.GetString("DetailsWrittenToLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect.
        /// </summary>
        internal static string DetectGameDirectoryButton {
            get {
                return ResourceManager.GetString("DetectGameDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBackground {
            get {
                object obj = ResourceManager.GetObject("DialogBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBorder {
            get {
                object obj = ResourceManager.GetObject("DialogBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogBorderLeft {
            get {
                object obj = ResourceManager.GetObject("DialogBorderLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DialogEdge {
            get {
                object obj = ResourceManager.GetObject("DialogEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} instead of {3}.
        /// </summary>
        internal static string DisplayDifferenceFormat {
            get {
                return ResourceManager.GetString("DisplayDifferenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string DisplayQuestionApply {
            get {
                return ResourceManager.GetString("DisplayQuestionApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your display settings differ from the recommended ones: {0}. Apply the recommended display settings?[rest of string was truncated].
        /// </summary>
        internal static string DisplayQuestionFormat {
            get {
                return ResourceManager.GetString("DisplayQuestionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep mine.
        /// </summary>
        internal static string DisplayQuestionKeep {
            get {
                return ResourceManager.GetString("DisplayQuestionKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ee_book {
            get {
                object obj = ResourceManager.GetObject("ee_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eegenericbutton_gold {
            get {
                object obj = ResourceManager.GetObject("eegenericbutton_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eegenericbutton_gold_pressed {
            get {
                object obj = ResourceManager.GetObject("eegenericbutton_gold_pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EmpireEarthLauncher {
            get {
                object obj = ResourceManager.GetObject("EmpireEarthLauncher", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Game Bit Depth ({1}) differs from Texture Bit Depth ({2}); the main menu can turn white and unr[rest of string was truncated].
        /// </summary>
        internal static string FindingBitDepthMismatchFormat {
            get {
                return ResourceManager.GetString("FindingBitDepthMismatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the folder {1} is not on a drive letter, so the "Installed From" values cannot point to it. Con[rest of string was truncated].
        /// </summary>
        internal static string FindingNotOnADriveFormat {
            get {
                return ResourceManager.GetString("FindingNotOnADriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the renderer is "{1}"; recommended for this installation is "{2}". Hide the hint if you chose i[rest of string was truncated].
        /// </summary>
        internal static string FindingRasterizerFormat {
            get {
                return ResourceManager.GetString("FindingRasterizerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen is only {0} pixels high; the menus of the game need at least 768. Some menus may not fit..
        /// </summary>
        internal static string FindingScreenTooLowFormat {
            get {
                return ResourceManager.GetString("FindingScreenTooLowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: 16-bit colors often freeze the game on Windows 8 and later. "Apply recommended display" sets 32[rest of string was truncated].
        /// </summary>
        internal static string FindingSixteenBitFormat {
            get {
                return ResourceManager.GetString("FindingSixteenBitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the game window ({1}) fits the screen only with the compatibility option HIGHDPIAWARE; without [rest of string was truncated].
        /// </summary>
        internal static string FindingWindowHighDpiFormat {
            get {
                return ResourceManager.GetString("FindingWindowHighDpiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the game window ({1}) is larger than the screen as the game sees it ({2}). "Apply recommended d[rest of string was truncated].
        /// </summary>
        internal static string FindingWindowLargerFormat {
            get {
                return ResourceManager.GetString("FindingWindowLargerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends ({0}).
        /// </summary>
        internal static string FriendsFormat {
            get {
                return ResourceManager.GetString("FriendsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends could not be read (see the log).
        /// </summary>
        internal static string FriendsUnreadable {
            get {
                return ResourceManager.GetString("FriendsUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Art of Conquest.
        /// </summary>
        internal static string GameArtOfConquest {
            get {
                return ResourceManager.GetString("GameArtOfConquest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string GameChoiceHeading {
            get {
                return ResourceManager.GetString("GameChoiceHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth folder:.
        /// </summary>
        internal static string GameDirectoryLabel {
            get {
                return ResourceManager.GetString("GameDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth installation not found.
        /// </summary>
        internal static string GameDirectoryNotFound {
            get {
                return ResourceManager.GetString("GameDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found, please choose the folder of {0}.
        /// </summary>
        internal static string GameDirectoryNotFoundHintFormat {
            get {
                return ResourceManager.GetString("GameDirectoryNotFoundHintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected in the launcher folder.
        /// </summary>
        internal static string GameDirectorySourceLauncherFolder {
            get {
                return ResourceManager.GetString("GameDirectorySourceLauncherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected from the game installation.
        /// </summary>
        internal static string GameDirectorySourceRegistry {
            get {
                return ResourceManager.GetString("GameDirectorySourceRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen manually.
        /// </summary>
        internal static string GameDirectorySourceUser {
            get {
                return ResourceManager.GetString("GameDirectorySourceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen manually, but the folder does not exist.
        /// </summary>
        internal static string GameDirectorySourceUserMissing {
            get {
                return ResourceManager.GetString("GameDirectorySourceUserMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth.
        /// </summary>
        internal static string GameEmpireEarth {
            get {
                return ResourceManager.GetString("GameEmpireEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not contain {0}: {1}  Use it anyway?.
        /// </summary>
        internal static string GameExecutableMissingFormat {
            get {
                return ResourceManager.GetString("GameExecutableMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game defaults.
        /// </summary>
        internal static string GameSettingsDefaultsHeading {
            get {
                return ResourceManager.GetString("GameSettingsDefaultsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string GameSettingsInstallationFormat {
            get {
                return ResourceManager.GetString("GameSettingsInstallationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off.
        /// </summary>
        internal static string HighDpiOffConfirmButton {
            get {
                return ResourceManager.GetString("HighDpiOffConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen is scaled to {0} %. Without HIGHDPIAWARE the game sees a smaller screen, and its window m[rest of string was truncated].
        /// </summary>
        internal static string HighDpiOffConfirmFormat {
            get {
                return ResourceManager.GetString("HighDpiOffConfirmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string HintBarDetails {
            get {
                return ResourceManager.GetString("HintBarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string HintBarHide {
            get {
                return ResourceManager.GetString("HintBarHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More hints on the Settings page: {0}.
        /// </summary>
        internal static string HintBarMoreFormat {
            get {
                return ResourceManager.GetString("HintBarMoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string HintsHeading {
            get {
                return ResourceManager.GetString("HintsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play page.
        /// </summary>
        internal static string HintShowColumn {
            get {
                return ResourceManager.GetString("HintShowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hints: the game settings fit together..
        /// </summary>
        internal static string HintsNone {
            get {
                return ResourceManager.GetString("HintsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing in {1}. Antivirus programs often delete or quarantine game files: restore it from the[rest of string was truncated].
        /// </summary>
        internal static string InstallationDamagedFormat {
            get {
                return ResourceManager.GetString("InstallationDamagedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth folder.
        /// </summary>
        internal static string InstallationGameFolderColumn {
            get {
                return ResourceManager.GetString("InstallationGameFolderColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string InstallationKindColumn {
            get {
                return ResourceManager.GetString("InstallationKindColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community setup.
        /// </summary>
        internal static string InstallationKindCommunity {
            get {
                return ResourceManager.GetString("InstallationKindCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed by the current community setup..
        /// </summary>
        internal static string InstallationKindCommunityHint {
            get {
                return ResourceManager.GetString("InstallationKindCommunityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older setup.
        /// </summary>
        internal static string InstallationKindCommunityLegacy {
            get {
                return ResourceManager.GetString("InstallationKindCommunityLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed by the community setup 1.7.2 or older. Run the current setup to update it..
        /// </summary>
        internal static string InstallationKindCommunityLegacyHint {
            get {
                return ResourceManager.GetString("InstallationKindCommunityLegacyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string InstallationKindForeign {
            get {
                return ResourceManager.GetString("InstallationKindForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed by the community setup, for example from the CD, by GOG or copied..
        /// </summary>
        internal static string InstallationKindForeignHint {
            get {
                return ResourceManager.GetString("InstallationKindForeignHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing: {0}.
        /// </summary>
        internal static string InstallationMissingProgramsFormat {
            get {
                return ResourceManager.GetString("InstallationMissingProgramsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was installed by a newer setup than this launcher knows. Please update the launcher..
        /// </summary>
        internal static string InstallationNewerSetupFormat {
            get {
                return ResourceManager.GetString("InstallationNewerSetupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string InstallationProductColumn {
            get {
                return ResourceManager.GetString("InstallationProductColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install folder.
        /// </summary>
        internal static string InstallationRootColumn {
            get {
                return ResourceManager.GetString("InstallationRootColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth and NeoEE are installed in the same folder ({0}). The launcher uses {1}, which was inst[rest of string was truncated].
        /// </summary>
        internal static string InstallationSharedRootFormat {
            get {
                return ResourceManager.GetString("InstallationSharedRootFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installations found:.
        /// </summary>
        internal static string InstallationsLabel {
            get {
                return ResourceManager.GetString("InstallationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Empire Earth installations....
        /// </summary>
        internal static string InstallationsSearching {
            get {
                return ResourceManager.GetString("InstallationsSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installations of {1} use the same game settings ({2}): the settings, including the game folder s[rest of string was truncated].
        /// </summary>
        internal static string InstallationsSharedSettingsFormat {
            get {
                return ResourceManager.GetString("InstallationsSharedSettingsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string InstallationStateColumn {
            get {
                return ResourceManager.GetString("InstallationStateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string InstallationStateDamaged {
            get {
                return ResourceManager.GetString("InstallationStateDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string InstallationStateFolderMissing {
            get {
                return ResourceManager.GetString("InstallationStateFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InstallationStateOk {
            get {
                return ResourceManager.GetString("InstallationStateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Settings.
        /// </summary>
        internal static string LauncherSettingsHeading {
            get {
                return ResourceManager.GetString("LauncherSettingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire Earth Launcher.
        /// </summary>
        internal static string LauncherTitle {
            get {
                return ResourceManager.GetString("LauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        internal static string LobbyProfileLabel {
            get {
                return ResourceManager.GetString("LobbyProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby profiles could not be read (see the log).
        /// </summary>
        internal static string LobbyProfilesUnreadable {
            get {
                return ResourceManager.GetString("LobbyProfilesUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        internal static string NavigationLauncher {
            get {
                return ResourceManager.GetString("NavigationLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string NavigationPlay {
            get {
                return ResourceManager.GetString("NavigationPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NavigationSettings {
            get {
                return ResourceManager.GetString("NavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lobby profile found.
        /// </summary>
        internal static string NoLobbyProfileFound {
            get {
                return ResourceManager.GetString("NoLobbyProfileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players ({0}).
        /// </summary>
        internal static string OnlinePlayersFormat {
            get {
                return ResourceManager.GetString("OnlinePlayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players (invalid server settings, see the log).
        /// </summary>
        internal static string OnlinePlayersInvalidSettings {
            get {
                return ResourceManager.GetString("OnlinePlayersInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players (...).
        /// </summary>
        internal static string OnlinePlayersLoading {
            get {
                return ResourceManager.GetString("OnlinePlayersLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players (unavailable).
        /// </summary>
        internal static string OnlinePlayersUnavailable {
            get {
                return ResourceManager.GetString("OnlinePlayersUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players (unavailable, see the log).
        /// </summary>
        internal static string OnlinePlayersUnavailableSeeLog {
            get {
                return ResourceManager.GetString("OnlinePlayersUnavailableSeeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerListNameColumn {
            get {
                return ResourceManager.GetString("PlayerListNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PlayerListStateColumn {
            get {
                return ResourceManager.GetString("PlayerListStateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string PlayerStateLobby {
            get {
                return ResourceManager.GetString("PlayerStateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string PlayerStatePlaying {
            get {
                return ResourceManager.GetString("PlayerStatePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string PlayerStateRoom {
            get {
                return ResourceManager.GetString("PlayerStateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ({0}).
        /// </summary>
        internal static string PlayerStateUnknownFormat {
            get {
                return ResourceManager.GetString("PlayerStateUnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_checked {
            get {
                object obj = ResourceManager.GetObject("radio_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_checked_disabled {
            get {
                object obj = ResourceManager.GetObject("radio_checked_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_unchecked {
            get {
                object obj = ResourceManager.GetObject("radio_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_unchecked_disabled {
            get {
                object obj = ResourceManager.GetObject("radio_unchecked_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove "Run as administrator".
        /// </summary>
        internal static string RemoveRunAsAdminButton {
            get {
                return ResourceManager.GetString("RemoveRunAsAdminButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset now.
        /// </summary>
        internal static string ResetConfirmButton {
            get {
                return ResourceManager.GetString("ResetConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the settings of {0} back to the recommended values for your Windows account?  Your current setti[rest of string was truncated].
        /// </summary>
        internal static string ResetConfirmFormat {
            get {
                return ResourceManager.GetString("ResetConfirmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset game settings.
        /// </summary>
        internal static string ResetGameSettingsButton {
            get {
                return ResourceManager.GetString("ResetGameSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was changed: the backup could not be written (details in the log)..
        /// </summary>
        internal static string ResultBackupFailed {
            get {
                return ResourceManager.GetString("ResultBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string ResultDone {
            get {
                return ResourceManager.GetString("ResultDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Your previous settings are saved in: {0}.
        /// </summary>
        internal static string ResultDoneFormat {
            get {
                return ResourceManager.GetString("ResultDoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be changed (details in the log)..
        /// </summary>
        internal static string ResultFailed {
            get {
                return ResourceManager.GetString("ResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be changed completely (details in the log). Double-click the backup to restor[rest of string was truncated].
        /// </summary>
        internal static string ResultFailedFormat {
            get {
                return ResourceManager.GetString("ResultFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible: this installation comes from a newer setup than this launcher knows. Please update the[rest of string was truncated].
        /// </summary>
        internal static string ResultNewerContract {
            get {
                return ResourceManager.GetString("ResultNewerContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Empire Earth folder (the folder of {0})..
        /// </summary>
        internal static string SelectGameDirectoryFormat {
            get {
                return ResourceManager.GetString("SelectGameDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom file....
        /// </summary>
        internal static string ThemeCustom {
            get {
                return ResourceManager.GetString("ThemeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme File (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ThemeFileFilter {
            get {
                return ResourceManager.GetString("ThemeFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme could not be loaded. Details have been written to {0}..
        /// </summary>
        internal static string ThemeNotLoadedFormat {
            get {
                return ResourceManager.GetString("ThemeNotLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string UiLanguageLabel {
            get {
                return ResourceManager.GetString("UiLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new language is used when the launcher starts the next time..
        /// </summary>
        internal static string UiLanguageRestartHint {
            get {
                return ResourceManager.GetString("UiLanguageRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows language.
        /// </summary>
        internal static string UiLanguageWindows {
            get {
                return ResourceManager.GetString("UiLanguageWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unchecked_disabled {
            get {
                object obj = ResourceManager.GetObject("unchecked_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred and the launcher has to close..
        /// </summary>
        internal static string UnexpectedErrorClosing {
            get {
                return ResourceManager.GetString("UnexpectedErrorClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. The launcher will try to continue..
        /// </summary>
        internal static string UnexpectedErrorContinuing {
            get {
                return ResourceManager.GetString("UnexpectedErrorContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
